"""Added totp field

Revision ID: 363b16a45424
Revises: 6db9bbbc6673
Create Date: 2024-09-24 20:44:11.570114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363b16a45424'
down_revision: Union[str, None] = '6db9bbbc6673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(), nullable=True))
    op.alter_column('users', 'two_factor_auth',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'two_factor_auth',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
