"""Added 2fa field in user model

Revision ID: 6db9bbbc6673
Revises: 7126c6fb3a4e
Create Date: 2024-09-23 22:02:48.788081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db9bbbc6673'
down_revision: Union[str, None] = '7126c6fb3a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_auth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_auth')
    # ### end Alembic commands ###
